todoapp:
  todoapp:
    env:
      mysqlHost: todoapp-mysql
    image:
      repository: gurukraj/gurutodoapp
      tag: "1.0"
  ports:
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  replicas: 3
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
mysql:
  mysql:
    image:
      repository: mysql
      tag: "latest"
  ports:
  - port: 3306
    targetPort: 0
  type: ClusterIP
mysqlConfigMap:
  mysqlDatabaseName: tododb
  mysqlRootUser: root
  mysqlServer: todoapp-mysql
  mysqlUserUsername: todouser
mysqlPass:
  password: "Testdb123@1"
pvc:
  mysqlPvClaim:
    storageRequest: 2Gi
  wpPvClaim:
    storageRequest: 2Gi
